rothgar/awesome-tmux

- README.md
Adding [tmux-fingers](https://github.com/morantron/tmux-fingers) to the list of plugins, because it's awesome :trollface:
> add tmux-fingers plugin

- README.md
This updates a reference to my book which is now out of date, but also adds two additional books I'm aware of, along with a new books section.
> Add section on tmux books

- README.md
While Vim centric, I believe my carefully crafted tmux configuration offers features worth looking at:
- self contained, just move `.tmux.conf` polyglot around
- powerline look & feel
- builtin variables: battery status, load average, SSH aware username and hostname display, ...
- improved maximize pane feature where a maximized pane can be further split
It sits in between a framework and personal settings. I believe it's worth discussing whether linking to it can give people ideas after having poked around and discovered how I did things.
Cheers
> added link to gpakosz/.tmux.git

- README.md
Added a new link to a plugin that I've made. It allows you to access your 1Password login items through a tmux pane.
> Add tmux-1password plugin

- README.md
tmuxpair is a script I created that serves as a session manager around tmux, for remote pair programming.
> Add link to tmuxpair

- README.md
Call me crazy, but I built a tmux integration plugin for Sublime Text last year, and I imagine a very select group of people like myself might use both tools together. This is added under the "Miscellaneous" section of the README.
> Add entry for sublime-tmux

- README.md
Added a tool to the Miscellaneous section.
> Added tmux-tail-f

- README.md
Add Themes section + link to [tomorrow](https://github.com/edouard-lopez/tmux-tomorrow/) theme
> add Themes section + link to tomorrow theme

- README.md
Two plugins for tmux status line:
* https://github.com/xamut/tmux-network-bandwidth — Show network bandwidth
* https://github.com/xamut/tmux-weather — Show current weather using wttr.in
> Add tmux-network-bandwidth and tmux-weather

- README.md
Add [tmux-nordvpn](https://github.com/maxrodrigo/tmux-nordvpn) to the Status Bar section.
> Add tmux-nordvpn under Status Bar

- README.md
https://github.com/xamut/tmux-spotify — Show a nice menu to manage Spotify application.
> Add tmux-spotify

- README.md
Let me know if I should document the inactivity a different way, or should remove the reference to tmux-urlview all together.
> Add tmux-urlscan, document tmux-urlview inactivity

- README.md
Adding another awesome plugin:
https://github.com/fcsonline/tmux-thumbs
> Adding tmux-thumbs to the list of plugins

- README.md
I would appreciate if my plugin `tilish` could be added to the list to make it more discoverable.
> Add tilish

- README.md
Adds the official [dracula theme](https://draculatheme.com/tmux)
> Add dracula theme

- README.md
> Add tmux-power theme

- README.md
adding my personal favorite theme
> [add] nord theme to readme

- README.md
Hey. I've created a tiny session manager in Go. Please let me know your thoughts about adding it to the list 🙂
> Add github.com/ivaaaan/smug

- .github/workflows/awesome_bot.yaml
This is an easy way to check the links to make sure they are valid with
each pull-request and push.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
> Gotta check those links.

- README.md
How to get tmux and pbcopy to play nice.
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
> Added a way to get the system clipboard on a mac

- README.md
> Added tmux-piavpn

- README.md
Tutorial is geared towards beginners and explains the difference between Windows, Panes, Sessions, and details how to configure them in addition to plugins, control keys, themes, etc.. Lots of images.  Think it will be helpful for people just starting out.
> Added a Tmux tutotial for Beginners

- README.md
Adds Tmux-world-clock tmux statusline plugin.
https://github.com/alexanderjeurissen/tmux-world-clock
> Add tmux-world-clock

- README.md
I wanted to share my tmux theme :boom:
> Add tmux-nova theme

- README.md
Add tmux-fuzzback plugin. Fuzzback lets you fuzzy search through your scrollback buffer using [fzf](https://github.com/junegunn/fzf).
> Add tmux-fuzzback plugin

- README.md
Muxile is a new tmux plugin I made that forwards your session to a webpage you can view on your phone, over WebSockets.
> Add Muxile

- README.md
Adds [tmux-autoreload](https://github.com/b0o/tmux-autoreload).
I'm not sure whether this should go under the Configuration section or the Plugins section; I've put it under Plugins for now.
> Add tmux-autoreload

- README.md
[tmux-super-fingers](https://github.com/artemave/tmux_super_fingers) is like fingers, but also opens files in vim.
> Add tmux-super-fingers plugin

- README.md
Status-bar:
tmux-mullvad
Plugins:
tmux-menus
tmux-mouse-swipe
> Some items I have made public

- README.md
Execute complex tmux commands in just a few keystrokes. tmux-modal
introduces a modal mode (e.g. like in Vim text editor) in tmux that is
designed to be efficient, easy to remember and comfortable.
> Add plugin tmux-modal

- README.md
A plugin that let you attach web browser sessions to your tmux sessions.
> added tmux-browser

- README.md
Names your tmux windows smartly.
> added tmux-window-name

- README.md
Displays packet loss % if at or above the specified threshold level
> tmux-packet-loss

- README.md
The plugin has matured over time and I think this better describes its purpose.
> Updated description of tmux-menus

- README.md
Tmux-split-statusbar is very nice when having lots of windows.
And it also provides a toggle function to turn it on and off.
> Add tmux-split-statusbar plugin

- README.md
https://github.com/thuanOwa/tmux-fzf-session-switch
> add tmux-fzf-session-switch

- README.md
Tool for adopting your tmux.conf after the capabilities of the destination tmux version and host type. Use the same config on every host you manage.
> Add tmux-conf

- README.md
A status bar plugin to display the current song playing on an MPD local server.
Also, stripping a couple of existing white spaces :)
> Add tmux-ludanta

- README.md
Adding my `t` script to the "Tools and session management" section 😄
> feat: add t smart tmux session manager resource

- README.md
Another one! A new plugin that renames tmux windows using nerd font icons. 🤓
> feat: add tmux-nerd-font-window-name plugin to status bar section

- README.md
[twm](https://github.com/vinnymeller/twm)
> Add twm to the list of session managers

- README.md
I have added a url for a tool that I built called disconnected that was written in TS and Deno and it creates all your config files in json instead of with yaml.
> feat: added url for Disconnected.

- README.md
Adding [tmux-dark-notify](https://github.com/erikw/tmux-dark-notify).
> Add tmux-dark-notify

- README.md
I added the coffee lover's theme :)
you can read more about it [HERE](https://github.com/catppuccin/tmux)
> Catppuccin for tmux

- README.md
Its very simple. I just added a link to tmux-pianobar inside the readme file
> Added tmux-pianobar

- README.md
This pull request updates the `tmux-notify` description to align with the [repository description](https://github.com/rickstaa/tmux-notify).
> docs: update 'tmux-notify' description

- README.md
It is minimal and only changes the status bar and gives a prefix
indicator.
> Added the theme i recently created

- README.md
Adding a spotify plugin to README that can add and play spotify playlists (and also do regular commands like play/pause/shuffle/repeat).Key bindings are editable in tmux.config for personal references :)
> Adding spotify playlists plugin

- README.md
Hey, I've made a cool little plugin that helps with filtering trough logs and wanted to add it to this list :)
> Add my tmux-filter plugin

- README.md
Hi!
I created this plugin inspired by other great plugins that lacked some crucial features for my workflow - 
- Preview
- Delete / Create / Rename sessions on the fly
- Create if not found
- Zoxide search for new names
- Lots of configurables
> Adding a new session manager: sessionx

- README.md
It's a tmux theme with bright colors and different segment support.
[tmux2k](https://github.com/2kabhishek/tmux2k)
> Add `tmux2k`

- README.md
It's an enhancement over tmux-tilish that aims to streamline few configs and add more shortcuts.
[tmux-tilit](https://github.com/2kabhishek/tmux-tilit)
> Adds `tmux-tilit`

- README.md
It's a easy to use session manager for tmux that integrates with tmuxinator
[tmux-tea](https://github.com/2kabhishek/tmux-tea)
> Add `tmux-tea`

- README.md
Hi!
I am the author of the rose-pine theme for tmux.
Was wondering if it could get added to the list of themes here. If so, I'd be very happy :)
Merry Christmas :christmas_tree:
> add: rose-pine theme

- README.md
Tome implements playbooks for tmux & vim
> add tome plugin

- README.md
Check what keys tmux can detect from the terminal being used.
> added tmux-keybtest in Configuration

- README.md
Add my project [muxbar](https://github.com/dlurak/muxbar).
> Add muxbar

- README.md
tmux-harpoon is a session bookmarking tool. Allows to quickly jump between bookmarks.
> add tmux-harpoon

- README.md
> Add moxide

- README.md
- tmux-tea was mentioned as tea
- tmux2k was mentioned in the themes section
- tmux-tilit's description was updated
> docs: update tmux-tea name and tmux2k category

- README.md
This is a library for golang to interact with tmux that I have developed. exposes a comprehensive API to interact with tmux. I hope this can be added to the list!
> docs: added gotmux tmux library

- README.md
Add a floating terminal window to your tmux session.
> added tmux floating pop up terminal plugin

- README.md
adds tmux-click-copy as per https://github.com/rothgar/awesome-tmux/issues/135
> add tmux-click-copy

- README.md
Add tmux-kubectx - shows current kubernetes context info in status bar
> Add tmux-kubectx

- README.md
Add [tmux-cookie-cutter](https://github.com/AranBorkum/tmux-cookie-cutter) to list of tmux plugins for window and session management
> Adds tmux-cookie-cutter plugin

- README.md
Manage and interact with (Devcontainers)[https://containers.dev]
> Added tmux-devcontainers

- README.md
Keeping the same format, added the following plugin: https://github.com/navahas/tmux-grimoire
> Add tmux plugin: tmux-grimoire
